# action.yml
name: 'ReSharper CLI CleanupCode'
description: 'TBD'
author: 'Artur Wincenciak (TeoVincent)'
branding:
  icon: 'terminal'
  color: 'purple'
inputs:
  fail_on_reformat_needed:
    description: 'TBD'
    required: false
    default: 'no'
  auto_commit:
    description: 'DBD'
    required: false
    default: 'yes'
outputs:
  status:
    description: 'DBD'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fail_on_reformat_needed }}
    - ${{ inputs.auto_commit }}