# action.yml
name: ReSharper CLI CleanupCode
description: Allows you to run ReSharper's CleanupCode Command-Line Tool in order to automatically clean up your code
author: 'Artur Wincenciak (TeoVincent)'
branding:
  icon: 'terminal'
  color: 'purple'

inputs:
  solution:
    description: 'Solution or project file to be cleaned up'
    required: true
  fail_on_reformat_needed:
    description: 'Determines whether the action should fail if the code needs to be reformatted'
    required: false
    default: 'no'
  auto_commit:
    description: 'Determines whether the action should automatically commit the changes made by the ReSharpers CleanupCode Command-Line Tool'
    required: false
    default: 'yes'
  jb_cleanup_code_arg:
    description: 'Additional arguments to pass to the ReSharpers CleanupCode Command-Line Tool. Configure the tool with command-line parameters e.g. --verbosity=INFO --profile=Built-in: Full Cleanup --exclude=**UnitTests/**.*'
    required: false
    default: '--verbosity=WARN'
  commit_message:
    description: 'The commit message to use if auto_commit is set to yes'
    required: false
    default: "Clean up code by ReSharper CLI CleanupCode Tool"
  commit_creator_email:
    description: 'The email address to use for the git user who creates the commit if auto_commit is set to yes'
    required: false
    default: "cleanupcode@github.action"
  commit_creator_name:
    description: 'The name to use for the git user who creates the commit if auto_commit is set to yes'
    required: false
    default: "CleanupCode Action"

runs:
  using: composite
  steps:
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh "${{ inputs.solution }}" "${{ inputs.fail_on_reformat_needed }}" "${{ inputs.auto_commit }}" "${{ inputs.jb_cleanup_code_arg }}" "${{ inputs.commit_message }}" "${{ inputs.commit_creator_email }}" "${{ inputs.commit_creator_name }}"
      shell: bash