# action.yml
name: Bash Action
description: A sample GitHub Action written in Bash

inputs:
  solution:
    description: 'TBD'
    required: true
  fail_on_reformat_needed:
    description: 'TBD'
    required: false
    default: 'no'
  auto_commit:
    description: 'TBD'
    required: false
    default: 'yes'
  jb_cleanup_code_arg:
    description: 'TBD'
    required: false
    default: '--verbosity=WARN'
  commit_message:
    description: 'TBD'
    required: false
    default: "Cleanup code"
  commit_creator_email:
    description: 'TBD'
    required: false
    default: "cleanupcode@github.action"
  commit_creator_name:
    description: 'TBD'
    required: false
    default: "CleanupCode GitHub Action"

runs:
  using: composite
  steps:
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh "${{ inputs.solution }}" "${{ inputs.fail_on_reformat_needed }}" "${{ inputs.auto_commit }}" "${{ inputs.jb_cleanup_code_arg }}" "${{ inputs.commit_message }}" "${{ inputs.commit_creator_email }}" "${{ inputs.commit_creator_name }}"
      shell: bash