# action.yml
name: ReSharper CLI CleanupCode
description: Allows you to run ReSharper's CleanupCode Command-Line Tool in order to automatically clean up your code
author: 'Artur Wincenciak (TeoVincent)'
branding:
  icon: 'terminal'
  color: 'purple'

inputs:
  solution:
    description: 'Solution or project file to be cleaned up'
    required: true
  fail_on_reformat_needed:
    description: 'Determines whether the action should fail if the code needs to be reformatted'
    required: false
    default: 'no'
  jb_cleanup_code_arg:
    description: 'Additional arguments to pass to the ReSharpers CleanupCode Command-Line Tool. Configure the tool with command-line parameters e.g. --verbosity=INFO --profile=Built-in: Full Cleanup --exclude=**UnitTests/**.*'
    required: false
    default: '--verbosity=WARN'

runs:
  using: composite
  steps:
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh "${{ inputs.solution }}" "${{ inputs.fail_on_reformat_needed }}" "${{ inputs.jb_cleanup_code_arg }}"
      shell: bash